language: python

python:
    - "3.10"

script:
    - cd data-processing-lib
    - echo pwd=$(pwd)
    - make venv test
    - echo pwd=$(pwd)
    - cd ../transforms
    - echo pwd=$(pwd)
    - make venv test-lib-src
