os:
    - linux
    - osx

language: python
python:
    - "3.10"
    - "3.11"

branches:
    only:
        - dev
        - main
env:
    matrix:
        - OPERATION=data-lib-test DOCKER=docker
        - OPERATION=transform-src-test   DIR=transforms/code DOCKER=docker
        - OPERATION=transform-src-test   DIR=transforms/language DOCKER=docker
        - OPERATION=transform-src-test   DIR=transforms/universal DOCKER=docker
        - OPERATION=transform-image DIR=transforms/code DOCKER=docker
        - OPERATION=transform-image DIR=transforms/language DOCKER=docker
        - OPERATION=transform-image DIR=transforms/universal DOCKER=docker
        - OPERATION=kfp-lib-test
        - OPERATION=kfp-compile
        - OPERATION=tools-test

# Enable/install podman
#before_install:
#    - sudo apt-get update
#    - sudo apt-get -y install podman
#    - podman machine init
#    - podman machine start
#    - podman info

script:
    - |
        case $OPERATION in
          kfp-lib-test)
              source kind/requirements.env
              export PATH=$PATH:/tmp/
              curl -Lo /tmp/kind https://kind.sigs.k8s.io/dl/v${KIND_VERSION}/kind-linux-amd64
              curl -fsSL -o /tmp/get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
              chmod 700 /tmp/get_helm.sh
              HELM_INSTALL_DIR=/tmp/ /tmp/get_helm.sh -v v${HELM_VERSION} --no-sudo
              chmod 777 /tmp/helm
              chmod 777 /tmp/kind
              curl -L https://dl.k8s.io/release/v${KUBECTL_VERSION}/bin/linux/amd64/kubectl -o /tmp/kubectl
              chmod 777 /tmp/kubectl
              export DEPLOY_KUBEFLOW=0
              # kind setup now relies on mc, which is not installed make -C kind setup || travis_terminate 1
              make -C kfp/kfp_support_lib build test || travis_terminate 1
          ;;
          kfp-compile)
                   make -C kfp/transform_workflows build || travis_terminate 1
          ;;
          data-lib-test)
                   make -C data-processing-lib DOCKER=${DOCKER} venv test || travis_terminate 1
          ;;
          transform-src-test)
                   make -C ${DIR} DOCKER=${DOCKER} venv test-src || travis_terminate 1
          ;;
          transform-image)
                   # Turn of publishing to public quay.io repo until we split the repos
                   #make -C ${DIR} DOCKER=${DOCKER} image test-image publish || travis_terminate 1
                   make -C ${DIR} DOCKER=${DOCKER} image test-image || travis_terminate 1
          ;;
          tools-test)
                   make -C tools DOCKER=${DOCKER} venv test-lib-src || travis_terminate 1
          ;;
          *)
              echo Unrecogognized operation "'"$OPERATION"'"
              travis_terminate 1
          ;;
        esac
