os: linux

language: python
python:
    - "3.10"

env:
    jobs:
        - DOCKER=docker

# Enable/install podman
before_install:
    - sudo mkdir /tmp
    - sudo chmod 777 /tmp
#    - sudo apt-get update
#    - sudo apt-get -y install podman
#    - podman machine init
#    - podman machine start
#    - podman info

script:
    - cd data-processing-lib
    - echo pwd=$(pwd)
    - make DOCKER=$DOCKER venv test
    - echo pwd=$(pwd)
    - cd ../transforms
    - echo pwd=$(pwd)
    - make DOCKER=$DOCKER venv test-lib-src
