os: linux

language: python
python:
    - "3.10"

env:
    jobs:
        - DOCKER=docker

branches:
    only:
        - dev
        - main

# Enable/install podman
#before_install:
#    - sudo apt-get update
#    - sudo apt-get -y install podman
#    - podman machine init
#    - podman machine start
#    - podman info

script: cd data-processing-lib
    && make DOCKER=$DOCKER venv test
    && cd ../transforms
    && make DOCKER=$DOCKER venv test-lib-src
