apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: kubeflow
    namespace: kubeflow
    annotations:
        nginx.ingress.kubernetes.io/use-regex: "true"
        nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
    ingressClassName: nginx
    rules:
        - http:
              paths:
                  - path: /kfp/(.*)
                    pathType: ImplementationSpecific
                    backend:
                        service:
                            name: ml-pipeline-ui
                            port:
                                name: http
